# Generated by Django 6.0.5 on 2026-06-01 10:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_image_profile",
                max_length=255,
                null=True,
                verbose_name="avatar",
            ),
        ),
    ]
